print("Date and time module..")
import datetime
now=datetime.datetime.now()
today =datetime.date.today()
print("Today's DATE TIME :",now)
print("Today's DATE :",today)
print("date components ")
print("Year:",now.year)
print("Month:",now.month)
print("Day:",now.day)
print("Hour:",now.hour)
print("Minute:",now.minute)
print("Second:",now.second)
print("Milli Seconds: ", now.microsecond)