print("hello world")
name=input("enter name: ")
age=int(input("enter age: "))
weight=float(input("enter weight: "))
status=bool(input("enter student status: "))
print("name: ",name)
print("age: ",age)
print("weight: ",weight)
print("Student Status: ",status)
print("Datatype of name :",type(name))
print("Datatype of age :",type(age))
print("Datatype of weight :",type(weight))
print("Datatype of Student Status:",type(status))
